src/CF/CentreBundle/Entity/Formateur.php
<?php

namespace CF\CentreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Asset;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Formateur
 *
 * @ORM\Table(name="formateur")
 * @ORM\Entity(repositoryClass="CF\CentreBundle\Entity\FormateurRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Formateur
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     * @Asset\Length(min=2, minMessage="Le nom doit contenir au moins 2 caractères.")
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     * @Asset\Length(min=2, minMessage="Le prénom doit contenir au moins 2 caractères.")
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="gsm", type="string", length=255)
     * @Asset\Regex(pattern="/^[0-9]{10}$/", match=true, message="Votre numéro de GSM doit contenir 10 chiffres.")
     */
    private $gsm;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     * @Asset\Email(message="{{ value }} n'est pas une adresse mail valide.")
     */
    private $email;

    // Slug
    /**
     * @Gedmo\Slug(fields={"prenom", "nom"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="CF\CentreBundle\Entity\Formation", mappedBy="formateur")
     */
    private $formations;

    // Retourne le nom complet du formateur
    public function getNomComplet()
    {
        return $this->nom.' '.$this->prenom;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Formateur
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Formateur
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set gsm
     *
     * @param string $gsm
     * @return Formateur
     */
    public function setGsm($gsm)
    {
        $this->gsm = $gsm;

        return $this;
    }

    /**
     * Get gsm
     *
     * @return string 
     */
    public function getGsm()
    {
        return $this->gsm;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Formateur
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Formateur
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->formations = new ArrayCollection();
    }

    /**
     * Add formations
     *
     * @param \CF\CentreBundle\Entity\Formation $formation
     * @return Formateur
     */
    public function addFormation(Formation $formation)
    {
        $this->formations[] = $formation;

        return $this;
    }

    /**
     * Remove formations
     *
     * @param \CF\CentreBundle\Entity\Formation $formation
     */
    public function removeFormation(Formation $formation)
    {
        $this->formations->removeElement($formation);

        $formation->setFormateur(null);
    }

    /**
     * Get formations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFormations()
    {
        return $this->formations;
    }

    /**
     * @ORM\PreRemove()
     */
    public function delFormation()
    {
        foreach($this->formations as $value)
            $this->removeFormation($value);
    }
}

src/CF/CentreBundle/Entity/Formation.php
<?php

namespace CF\CentreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Asset;

/**
 * Formation
 *
 * @ORM\Table(name="formation")
 * @ORM\Entity(repositoryClass="CF\CentreBundle\Entity\FormationRepository")
 */
class Formation
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     * @Asset\NotBlank(message="Le nom de la formation ne peut pas être vide.")
     */
    private $nom;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     * @Asset\DateTime()
     */
    private $date;

    /**
     * @var float
     *
     * @ORM\Column(name="duree", type="float")
     * @Asset\Type(type="float", message="La durée de la formation n'est pas un nombre valide.")
     */
    private $duree;

    // Slug
    /**
     * @Gedmo\Slug(fields={"nom"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity="CF\CentreBundle\Entity\Formateur", inversedBy="formations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $formateur;

    // Préremplissage de la date du jour
    public function __construct()
    {
        $this->date = new \DateTime();
    }

    public function setFormateur(Formateur $formateur = null)
    {
        $this->formateur = $formateur;

        if($formateur !== null)
            $this->formateur->addFormation($this);

        return $this;
    }

    public function getFormateur()
    {
        return $this->formateur;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Formation
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Formation
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set duree
     *
     * @param float $duree
     * @return Formation
     */
    public function setDuree($duree)
    {
        $this->duree = $duree;

        return $this;
    }

    /**
     * Get duree
     *
     * @return float 
     */
    public function getDuree()
    {
        return $this->duree;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Formation
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
}

src/CF/CentreBundle/Form/FormationType.php
<?php

namespace CF\CentreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FormationType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', 'text')
            ->add('date', 'datetime')
            ->add('duree', 'number')
            ->add('formateur', 'entity', array(
                'class' => 'CFCentreBundle:Formateur',
                'property' => 'getNomComplet',
                'multiple' => false,
                'required' => false,
                'empty_value' => '-- Aucun formateur --',
            ))
            ->add('ajouter', 'submit')
            ->add('effacer', 'reset')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CF\CentreBundle\Entity\Formation'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'cf_centrebundle_formation';
    }
}

src/CF/CentreBundle/Controller/FormationController.php
<?php

namespace CF\CentreBundle\Controller;

use CF\CentreBundle\Entity\Formation;
use CF\CentreBundle\Form\FormationType;
use CF\CentreBundle\Form\FormationEditType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class FormationController extends Controller
{
   // Affichage de la liste des formations
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $listFormations = $em->getRepository('CFCentreBundle:Formation')->findAll();

        return $this->render('CFCentreBundle:Formation:index.html.twig', array(
            'listFormations' => $listFormations,
        ));
    }

    // Ajout d'une nouvelle formation
    public function addAction(Request $request)
    {
        $formation = new Formation();

        $form = $this->createForm(new FormationType(), $formation);
        // Si les données du formulaire sont valides
        if($form->handleRequest($request)->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($formation);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info', 'La formation a bien été créée.');

            return $this->redirect($this->generateUrl('cf_centre_formation'));
        }

        return $this->render('CFCentreBundle:Formation:ajouter.html.twig', array(
            'form' => $form->createView(),
        ));
    }
    // Modification d'une formation
    public function modifAction($slug, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $formation = $em->getRepository('CFCentreBundle:Formation')
            ->findFormation($slug);
        // Si la formation n'existe pas
        if(null === $formation)
            return $this->createNotFoundException("La formation n'existe pas.");

        $form = $this->createForm(new FormationEditType(), $formation);
        // Si données correctes
        if($form->handleRequest($request)->isValid())
        {
            $em->flush();

            $request->getSession()->getFlashBag()->add('info', 'La formation a bien été modifiée.');

            return $this->redirect($this->generateUrl('cf_centre_formation'));
        }

        return $this->render('CFCentreBundle:Formation:modifier.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    // Suppression d'une formation
    public function delAction($slug, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $formation = $em->getRepository('CFCentreBundle:Formation')
            ->findFormation($slug);

        if(null === $formation)
            throw $this->createNotFoundException("Cette formation n'existe pas.");

        $form = $this->createFormBuilder()->getForm();

        if($form->handleRequest($request)->isValid())
        {
            $em->remove($formation);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info', 'La formation a bien été supprimée');

            return $this->redirect($this->generateUrl('cf_centre_formation'));
        }

        return $this->render('CFCentreBundle:Formation:supprimer.html.twig', array(
            'formation' => $formation,
            'form' => $form->createView(),
        ));
    }
}

src/CF/CentreBundle/Resources/views/Formation/ajouter.html.twig
{% extends "CFCentreBundle::layout.html.twig" %}

{% block title %} Ajout d'une formation - {{ parent() }} {% endblock %}

{% block body %}
    <h1>Ajout d'une formation</h1>
    <p>Afin d'ajouter une formation, merci de compléter le formulaire ci-dessous.</p>

    {{ include("CFCentreBundle:Formation:form.html.twig") }}

{% endblock %}

src/CF/CentreBundle/Resources/views/Formation/form.html.twig
{{ form_start(form, {'attr':{'class':'form-horizontal'}}) }}
<!-- Affichage des erreurs du formulaire -->
{% if not form.vars.valid %}
    <div class="alert alert-danger">
        {{ form_errors(form.nom) }}
        {{ form_errors(form.date) }}
        {{ form_errors(form.duree) }}
    </div>
{% endif %}

<div class="form-group">
    {{ form_label(form.nom, "Nom", {'label_attr':{'class':'col-sm-1 control-label'}}) }}
    <div class="col-sm-3">
        {{ form_widget(form.nom, {'attr':{'class':'form-control'}}) }}
    </div>
</div>

<div class="form-group">
    {{ form_label(form.date, "Date", {'label_attr':{'class':'col-sm-1 control-label'}}) }}
    <div class="col-sm-3">
        {{ form_widget(form.date) }}
    </div>
</div>

<div class="form-group">
    {{ form_label(form.duree, "Durée", {'label_attr':{'class':'col-sm-1 control-label'}}) }}
    <div class="col-sm-1 input-group">
        {{ form_widget(form.duree, {'attr':{'class':'form-control'}}) }}
        <span class="input-group-addon">h</span>
    </div>
</div>

<div class="form-group">
    {{ form_label(form.formateur, 'Formateur', {'label_attr':{'class':'col-sm-1 control-label'}}) }}
    <div class="col-sm-3">
        {{ form_widget(form.formateur) }}
    </div>
</div>

<a href="{{ path('cf_centre_formation') }}" class="btn btn-default col-lg-offset-1">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Retour à la liste
</a>
{% if form.ajouter is defined %}
    {{ form_widget(form.ajouter, {'attr':{'class':'btn btn-primary'}}) }}
{% else %}
    {{ form_widget(form.modifier, {'attr':{'class':'btn btn-primary'}}) }}
{% endif %}

{{ form_widget(form.effacer, {'attr':{'class':'btn btn-danger'}}) }}

{{ form_rest(form) }}
{{ form_end(form) }}

src/CF/CentreBundle/Resources/views/Formation/index.html.twig
{% extends "CFCentreBundle::layout.html.twig" %}

{% block title %} Liste des formations - {{ parent() }}{% endblock %}

{% block body %}

    <h1>Liste des formations</h1>
    <table class="table">
        <tr><th>Titre</th><th>Date</th><th>Durée</th><th>Formateur</th><th>Action</th></tr>
        {% for formation in listFormations %}
            <tr>
                <td>{{ formation.nom }}</td>
                <td>{{ formation.date|date('d/m/Y à H:i') }}</td>
                <td>{{ formation.duree }}</td>
                <td>
                    {% if formation.formateur.nomComplet is defined %}
                        {{ formation.formateur.nomComplet }}
                    {% else %}
                        Auncun formateur désigné
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('cf_centre_formation_modif', {'slug': formation.slug}) }}" class="btn btn-info">
                        <span class="glyphicon glyphicon-edit"></span>
                        Modifier
                    </a>
                    <a href="{{ path('cf_centre_formation_del', {'slug': formation.slug}) }}" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                        Supprimer
                    </a>
                </td>
            </tr>
        {% else %}
            <tr><td colspan="5" class="text-center">Il n'y a encore aucune formation</td></tr>
        {% endfor %}
    </table>
    <p class="text-right">
        <a href="{{ path('cf_centre_formation_add') }}" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>
            Ajouter une formation
        </a>
    </p>
{% endblock %}

src/CF/CentreBundle/Resources/views/Formation/modifier.html.twig
{% extends "CFCentreBundle::layout.html.twig" %}

{% block title %} Modification d'une formation - {{ parent() }} {% endblock %}

{% block body %}
    <h1>Modification d'une formation</h1>

    {{ include("CFCentreBundle:Formation:form.html.twig") }}

{% endblock %}

src/CF/CentreBundle/Resources/views/Formation/supprimer.html.twig
{% extends "CFCentreBundle::layout.html.twig" %}

{% block title %} Suppression d'une formation - {{ parent() }} {% endblock %}

{% block body %}
    <h1>Suppression d'une formation</h1>
    <p>Vous êtes sûr le point de supprimer la formation <strong>{{ formation.nom }}</strong>
        {% if formation.formateur is not null %} donner par <strong>{{ formation.formateur.nomComplet }}</strong>{% endif %}.</p>

    <form method="post">
        <a href="{{ path('cf_centre_formateur') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span>
            Supprimer définitivement
        </button>
        {{ form_rest(form) }}
    </form>

{% endblock %}